import type { Finding, Run } from "./types.ts";

/**
 * The morning briefing.
 *
 * Computed from run data, never generated by a model. Three reasons, in order
 * of importance:
 *
 *   1. A product whose entire claim is "reports only what it can prove" cannot
 *      have its daily summary be the one component that invents things.
 *   2. It is instant, free, and works with no network and no credentials.
 *   3. It is testable. A spoken summary that is wrong once is never trusted
 *      again, and you cannot unit-test a paraphrase.
 *
 * The briefing is also written to be HEARD, not read. Short sentences, numbers
 * spoken as words where it helps, no punctuation that a speech synthesiser will
 * mangle, and the thing that needs a decision said first.
 */

export type BriefingStatus = "no-data" | "clear" | "attention" | "blocked";

export interface BriefingSegment {
  /** Short label for the visual list. */
  label: string;
  /** Sentence intended for speech. */
  text: string;
  tone: "neutral" | "good" | "warn" | "bad";
}

export interface Briefing {
  greeting: string;
  headline: string;
  status: BriefingStatus;
  segments: BriefingSegment[];
  /** The whole thing as one utterance. */
  spoken: string;
  needsAttention: Finding[];
  runId?: string;
}

function greetFor(hour: number): string {
  if (hour < 5) return "Working late";
  if (hour < 12) return "Good morning";
  if (hour < 18) return "Good afternoon";
  return "Good evening";
}

/** "2 hours ago", spoken naturally rather than as a timestamp. */
export function relativeTime(then: string, now: Date): string {
  const ms = now.getTime() - Date.parse(then);
  if (!Number.isFinite(ms) || ms < 0) return "just now";

  const minutes = Math.round(ms / 60_000);
  if (minutes < 2) return "just now";
  if (minutes < 60) return `${minutes} minutes ago`;

  const hours = Math.round(minutes / 60);
  if (hours === 1) return "an hour ago";
  if (hours < 24) return `${hours} hours ago`;

  const days = Math.round(hours / 24);
  return days === 1 ? "yesterday" : `${days} days ago`;
}

function plural(n: number, one: string, many = `${one}s`): string {
  return `${n} ${n === 1 ? one : many}`;
}

/**
 * Findings present in the latest run that were not in the previous one. Matched
 * on id, which is a hash of axis, route, locator and title - so the same defect
 * across two runs is recognised as the same defect.
 */
export function newSince(latest: Run, previous?: Run): Finding[] {
  if (!previous) return latest.findings.filter((f) => f.tier === "CONFIRMED");
  const before = new Set(previous.findings.map((f) => f.id));
  return latest.findings.filter((f) => f.tier === "CONFIRMED" && !before.has(f.id));
}

/** Confirmed last time, absent now. Likely fixed, and worth saying so. */
export function resolvedSince(latest: Run, previous?: Run): Finding[] {
  if (!previous) return [];
  const now = new Set(latest.findings.map((f) => f.id));
  return previous.findings.filter((f) => f.tier === "CONFIRMED" && !now.has(f.id));
}

/**
 * How the briefing addresses you.
 *
 * "formal" is the measured, deferential register - the thing that actually
 * makes an assistant read as an assistant, far more than any particular
 * timbre does. It only changes address and cadence; it never changes a fact,
 * because the phrasing layer must not be able to soften a finding.
 */
export type Address = "plain" | "formal";

export function buildBriefing(opts: {
  latest?: Run;
  previous?: Run;
  now?: Date;
  /** Name to greet. Omitted entirely rather than guessed. */
  name?: string;
  address?: Address;
}): Briefing {
  const now = opts.now ?? new Date();
  const formal = opts.address === "formal";
  const greeting =
    greetFor(now.getHours()) +
    (opts.name ? `, ${opts.name}` : formal ? ", sir" : "");
  const segments: BriefingSegment[] = [];

  /* --- nothing to report ------------------------------------------------ */

  if (!opts.latest) {
    return {
      greeting,
      headline: "No runs yet",
      status: "no-data",
      segments: [
        {
          label: "No data",
          text: "There are no runs recorded for this project yet, so I have nothing to report.",
          tone: "neutral",
        },
      ],
      spoken: `${greeting}. There are no runs recorded for this project yet, so I have nothing to report.`,
      needsAttention: [],
    };
  }

  const run = opts.latest;
  const confirmed = run.findings.filter((f) => f.tier === "CONFIRMED");
  const criticals = confirmed.filter((f) => f.severity === "critical");
  const highs = confirmed.filter((f) => f.severity === "high");
  const unverified = run.findings.filter((f) => f.tier === "PLAUSIBLE" || f.tier === "QUESTION");

  const totals = run.axes.reduce(
    (acc, a) => ({
      failed: acc.failed + (a.results?.failed ?? 0),
      skipped: acc.skipped + (a.results?.skipped ?? 0),
    }),
    { failed: 0, skipped: 0 },
  );

  const when = relativeTime(run.startedAt, now);
  const feature = run.request?.feature;

  segments.push({
    label: "Last run",
    text: feature
      ? `The last run finished ${when}, on ${feature}.`
      : `The last run finished ${when}.`,
    tone: "neutral",
  });

  /* --- blocked outranks everything -------------------------------------- */

  let status: BriefingStatus = "clear";

  if (run.status === "blocked" || run.guard.mode === "aborted" || run.boot?.verified === false) {
    status = "blocked";
    const why =
      run.guard.mode === "aborted"
        ? "the safety guard refused the target"
        : run.boot?.verified === false
          ? "the application could not be proved to start"
          : "it was blocked before completing";
    segments.push({
      label: "Blocked",
      text: `That run did not produce a result, because ${why}. Nothing was actually tested.`,
      tone: "bad",
    });
  }

  /* --- what needs a decision, first -------------------------------------- */

  if (criticals.length) {
    status = status === "blocked" ? status : "attention";
    segments.push({
      label: "Critical",
      text: `${plural(criticals.length, "confirmed critical finding")} ${criticals.length === 1 ? "needs" : "need"} your attention. ${criticals[0].title}.`,
      tone: "bad",
    });
  }

  if (highs.length) {
    status = status === "blocked" ? status : "attention";
    segments.push({
      label: "High",
      text: `Also ${plural(highs.length, "confirmed high severity finding")}.`,
      tone: "warn",
    });
  }

  const fresh = newSince(run, opts.previous);
  const fixed = resolvedSince(run, opts.previous);

  if (opts.previous && fresh.length) {
    segments.push({
      label: "New",
      text: `${plural(fresh.length, "finding")} ${fresh.length === 1 ? "is" : "are"} new since the previous run.`,
      tone: "warn",
    });
  }

  if (fixed.length) {
    segments.push({
      label: "Resolved",
      text: `${plural(fixed.length, "finding")} from the previous run ${fixed.length === 1 ? "is" : "are"} gone.`,
      tone: "good",
    });
  }

  const drafts = confirmed.filter((f) => f.tracker?.status === "drafted");
  if (drafts.length) {
    segments.push({
      label: "Awaiting you",
      text: `${plural(drafts.length, "ticket draft")} ${drafts.length === 1 ? "is" : "are"} waiting for your approval. Nothing is filed until you say so.`,
      tone: "warn",
    });
  }

  /* --- honesty about what the result is worth ---------------------------- */

  if (totals.skipped > 0) {
    status = status === "blocked" ? status : "attention";
    segments.push({
      label: "Skipped",
      text: `${plural(totals.skipped, "spec")} did not run. A skipped check is an open question, not a pass.`,
      tone: "warn",
    });
  }

  const visited = run.coverage?.routesVisited ?? 0;
  const known = run.coverage?.routesKnown ?? 0;
  if (known > 0) {
    const pct = Math.round((visited / known) * 100);
    if (pct < 50) {
      segments.push({
        label: "Coverage",
        text: `Coverage was only ${pct} percent of known routes, so treat a clean result carefully.`,
        tone: "warn",
      });
    } else {
      segments.push({
        label: "Coverage",
        text: `Coverage was ${pct} percent of known routes.`,
        tone: "neutral",
      });
    }
  } else {
    // Unknown coverage cannot be reported as clear. "Nothing was found" and
    // "nothing was looked at" produce identical output, and only one of them is
    // good news - so the status is downgraded rather than the caveat merely
    // being appended underneath a green headline.
    if (status === "clear") status = "attention";
    segments.push({
      label: "Coverage",
      text: "Coverage is unknown for that run, so a clean result cannot really be interpreted.",
      tone: "warn",
    });
  }

  if (unverified.length) {
    segments.push({
      label: "Unverified",
      text: `${plural(unverified.length, "finding")} could not be confirmed either way. Neither proven bugs nor proven fine.`,
      tone: "neutral",
    });
  }

  const skippedAxes = run.axes.filter((a) => a.status === "skipped" || a.status === "error");
  if (skippedAxes.length) {
    segments.push({
      label: "Not covered",
      text: `${plural(skippedAxes.length, "axis", "axes")} did not run: ${skippedAxes.map((a) => a.key).join(", ")}.`,
      tone: "warn",
    });
  }

  /* --- the all-clear, stated carefully ----------------------------------- */

  if (status === "clear" && !confirmed.length && !totals.failed) {
    segments.push({
      label: "Clear",
      text:
        known > 0 && visited / known >= 0.5
          ? "Nothing was confirmed against the app, and coverage was reasonable."
          : "Nothing was confirmed, but coverage was thin, so that is not the same as being fine.",
      tone: known > 0 && visited / known >= 0.5 ? "good" : "warn",
    });
  }

  const headline =
    status === "blocked"
      ? "Last run was blocked"
      : criticals.length
        ? `${plural(criticals.length, "critical finding")}`
        : confirmed.length
          ? `${plural(confirmed.length, "confirmed finding")}`
          : "Nothing confirmed";

  const needsAttention = [...criticals, ...highs];

  if (formal) {
    segments.push({
      label: "Standing by",
      text:
        needsAttention.length > 0
          ? "I would suggest starting there. Standing by."
          : "Nothing further to report. Standing by.",
      tone: "neutral",
    });
  }

  return {
    greeting,
    headline,
    status,
    segments,
    // Assembled last so the spoken form and the visible list can never diverge.
    spoken: [`${greeting}.`, ...segments.map((s) => s.text)].join(" "),
    needsAttention,
    runId: run.runId,
  };
}

/* ---------------------------------------------------------------- intents */

export type IntentName =
  | "briefing"
  | "criticals"
  | "blocked"
  | "skipped"
  | "coverage"
  | "unknown";

/**
 * Deliberately a keyword matcher rather than a model call.
 *
 * The command set is small and fixed, so a model would add latency, cost and a
 * new failure mode in exchange for nothing. It also means voice works offline
 * and with no credentials configured.
 */
export function parseIntent(utterance: string): IntentName {
  const text = utterance.toLowerCase();
  const has = (...words: string[]) => words.some((w) => text.includes(w));

  if (has("critical", "worst", "urgent", "serious")) return "criticals";
  if (has("blocked", "block", "fail to start", "why did it stop")) return "blocked";
  if (has("skip", "skipped", "not run", "didn't run", "did not run")) return "skipped";
  if (has("coverage", "covered", "how much", "how thorough")) return "coverage";
  if (has("how are we", "how is it", "status", "brief", "morning", "report", "doing", "update")) {
    return "briefing";
  }
  return "unknown";
}

/** Answers one intent from the same computed briefing, so nothing can disagree. */
export function answerIntent(intent: IntentName, briefing: Briefing): string {
  const find = (label: string) => briefing.segments.find((s) => s.label === label)?.text;

  switch (intent) {
    case "briefing":
      return briefing.spoken;
    case "criticals":
      return (
        find("Critical") ??
        (briefing.status === "no-data"
          ? "There are no runs yet."
          : "There are no confirmed critical findings.")
      );
    case "blocked":
      return find("Blocked") ?? "The last run was not blocked. It completed.";
    case "skipped":
      return find("Skipped") ?? find("Not covered") ?? "Nothing was skipped in the last run.";
    case "coverage":
      return find("Coverage") ?? "Coverage was not recorded for that run.";
    case "unknown":
      return "I can tell you how we are doing, what is critical, what was blocked, what was skipped, or what the coverage was.";
  }
}

/* ------------------------------------------------------------- verdict line */

export type VerdictTone =
  | "clear"
  | "confirmed"
  | "unconfirmed"
  | "unrecorded"
  | "blocked"
  | "pending";

/**
 * The headline for a run, derived from what the run actually holds.
 *
 * The dashboard used to print "DETECTIONS CONFIRMED" for any run with the
 * `findings` status. Once triage started grading, a run could carry that
 * headline above a count of zero confirmed - the header claiming more than the
 * evidence supports, which is the one thing this product cannot do.
 *
 * The awkward case is the last one: tests went red and no finding was recorded.
 * That is a gap in the run, not a clean result, and it is coloured as a failure
 * so it cannot be misread as one.
 */
export function verdictLine(run: Run): { tone: VerdictTone; text: string } {
  if (run.status === "blocked") return { tone: "blocked", text: "BLOCKED" };
  if (run.status === "error") return { tone: "blocked", text: "ERROR" };
  if (run.status === "running") return { tone: "pending", text: "RUNNING" };
  if (run.status === "cancelled") return { tone: "pending", text: "CANCELLED" };

  if (run.status === "passed") return { tone: "clear", text: "ALL CLEAR" };

  const confirmed = run.findings.filter((f) => f.tier === "CONFIRMED").length;
  if (confirmed > 0) {
    return { tone: "confirmed", text: `${confirmed} CONFIRMED` };
  }

  if (!run.findings.length) {
    const failed = run.axes.reduce((n, a) => n + (a.results?.failed ?? 0), 0);
    return {
      tone: "unrecorded",
      text: failed ? "FAILURES UNRECORDED" : "NO RESULT",
    };
  }

  return { tone: "unconfirmed", text: `${run.findings.length} UNCONFIRMED` };
}


/**
 * What a run should be called when nobody named it.
 *
 * "Untitled run" tells a reader nothing, and most runs are launched without a
 * `--feature`. The axes that actually ran are both accurate and the thing
 * someone scanning a list of runs is looking for.
 */
export function runTitle(run: Run): string {
  if (run.request?.feature?.trim()) return run.request.feature.trim();

  const ran = run.axes.filter((a) => a.status === "done").map((a) => a.key);
  if (ran.length === 1) return ran[0];
  if (ran.length > 1 && ran.length <= 3) return ran.join(" + ");
  if (ran.length > 3) return `${ran.length} axes`;

  // Nothing ran. Say which axes were asked for rather than implying a full run.
  const asked = run.request?.axes ?? [];
  return asked.length ? `${asked.join(", ")} (did not run)` : "no axes ran";
}
