import { spawn } from "node:child_process";
import { readFile, writeFile, mkdir, symlink, readlink, rm } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import type { AxisResults, Profile } from "./types.ts";

/**
 * Locate Playwright's own CLI rather than shelling out to `npx playwright`.
 *
 * The target project is not required to depend on Playwright, and under pnpm
 * the binary is not on the path from an arbitrary cwd, so `npx` there fails
 * with "command not found". Resolving the module gives a stable absolute path
 * we can run with the current Node binary from any directory.
 */
export function resolvePlaywrightCli(): string | null {
  const req = createRequire(import.meta.url);

  // The package's exports map publishes the runner as "./cli" (no extension),
  // so a plain "cli.js" specifier is rejected even though the file is there.
  try {
    return req.resolve("@playwright/test/cli");
  } catch {
    /* fall through */
  }

  // Older layouts, and any version whose exports map changes again: locate the
  // package root through its package.json and go to the file directly.
  try {
    return path.join(path.dirname(req.resolve("@playwright/test/package.json")), "cli.js");
  } catch {
    return null;
  }
}

/**
 * Counts come from here - the Playwright JSON reporter - and never from an
 * agent's summary. An agent can describe a run any way it likes; these numbers
 * are the ones the UI shows.
 */
export function parsePlaywrightReport(report: unknown): AxisResults {
  const r = report as {
    stats?: { expected?: number; unexpected?: number; flaky?: number; skipped?: number; duration?: number };
  };

  if (r?.stats) {
    return {
      passed: r.stats.expected ?? 0,
      failed: r.stats.unexpected ?? 0,
      skipped: r.stats.skipped ?? 0,
      flaky: r.stats.flaky ?? 0,
      durationMs: Math.round(r.stats.duration ?? 0),
    };
  }

  // Older/partial reports: walk the suite tree rather than reporting zeros,
  // which would read as "nothing failed".
  const counts = { passed: 0, failed: 0, skipped: 0, flaky: 0, durationMs: 0 };
  const walk = (node: unknown): void => {
    const n = node as {
      suites?: unknown[];
      specs?: Array<{ tests?: Array<{ status?: string; results?: Array<{ duration?: number }> }> }>;
    };
    for (const spec of n?.specs ?? []) {
      for (const t of spec.tests ?? []) {
        counts.durationMs += (t.results ?? []).reduce((s, x) => s + (x.duration ?? 0), 0);
        switch (t.status) {
          case "expected":
            counts.passed++;
            break;
          case "unexpected":
            counts.failed++;
            break;
          case "flaky":
            counts.flaky++;
            break;
          case "skipped":
            counts.skipped++;
            break;
        }
      }
    }
    for (const child of n?.suites ?? []) walk(child);
  };
  walk(report);
  return counts;
}

/** A Playwright config generated per run, so we never mutate the target repo's own config. */
export function renderPlaywrightConfig(opts: {
  baseURL: string;
  testDir: string;
  outputDir: string;
  /**
   * Which files this process may run. Required in practice: every axis shares
   * one scratch directory, so without it each axis runs every other axis' specs
   * too - inflating the counts and filing each finding once per axis, under
   * whichever axis happened to pick it up.
   */
  testMatch?: string[];
  storageState?: string;
  viewport?: { width: number; height: number };
  retries?: number;
}): string {
  return `import { defineConfig } from "@playwright/test";

// Generated by clarvis. Do not edit - regenerated per run.
export default defineConfig({
  testDir: ${JSON.stringify(opts.testDir)},${
    opts.testMatch ? `\n  testMatch: ${JSON.stringify(opts.testMatch)},` : ""
  }
  outputDir: ${JSON.stringify(path.join(opts.outputDir, "artifacts"))},
  fullyParallel: false,
  forbidOnly: true,
  retries: ${opts.retries ?? 0},
  reporter: [["json", { outputFile: ${JSON.stringify(path.join(opts.outputDir, "report.json"))} }]],
  use: {
    baseURL: ${JSON.stringify(opts.baseURL)},
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "off",
    ignoreHTTPSErrors: true,${
      opts.storageState ? `\n    storageState: ${JSON.stringify(opts.storageState)},` : ""
    }${
      opts.viewport
        ? `\n    viewport: { width: ${opts.viewport.width}, height: ${opts.viewport.height} },`
        : ""
    }
  },
});
`;
}

/**
 * Specs and the generated config live inside the *target* project, which has no
 * reason to depend on Playwright. Link our copy into `.clarvis/node_modules` so
 * `import { test } from "@playwright/test"` resolves by the normal upward walk,
 * without touching the target's own `node_modules` or package.json.
 */
export async function linkSpecDeps(clarvisRoot: string): Promise<void> {
  const req = createRequire(import.meta.url);
  let pkgDir: string;
  try {
    pkgDir = path.dirname(req.resolve("@playwright/test/package.json"));
  } catch {
    return;
  }

  const scopeDir = path.join(clarvisRoot, "node_modules", "@playwright");
  const link = path.join(scopeDir, "test");
  await mkdir(scopeDir, { recursive: true });

  try {
    const existing = await readlink(link);
    if (path.resolve(scopeDir, existing) === path.resolve(pkgDir)) return;
    await rm(link, { force: true, recursive: true });
  } catch {
    // Not a symlink, or absent. Remove whatever is there and relink.
    await rm(link, { force: true, recursive: true }).catch(() => {});
  }

  await symlink(pkgDir, link, "junction").catch(() => {});
}

/** Playwright treats --grep as a regex. A literal title must be escaped. */
export function escapeForGrep(title: string): string {
  return title.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export interface AxisRunOutcome {
  results: AxisResults;
  exitCode: number;
  reportPath: string;
  stderr: string;
}

/**
 * Run one axis' specs in its own Playwright process.
 *
 * Each axis gets its own browser process rather than sharing one, so axes can
 * run concurrently without fighting over a single page.
 */
export async function runAxisSpecs(opts: {
  axisKey: string;
  profile: Profile;
  specDir: string;
  /** Spec filenames, relative to specDir. Defaults to `<axis>-*.spec.ts`. */
  specFiles?: string[];
  /** Run only tests whose title matches. Used by triage to re-run one test. */
  grep?: string;
  outputDir: string;
  baseURL: string;
  storageState?: string;
  playwrightBin?: string;
  timeoutMs?: number;
  log?: (line: string) => void;
}): Promise<AxisRunOutcome> {
  const log = opts.log ?? (() => {});
  await mkdir(opts.outputDir, { recursive: true });
  await linkSpecDeps(path.resolve(opts.specDir, ".."));

  const configPath = path.join(opts.outputDir, "playwright.config.ts");
  await writeFile(
    configPath,
    renderPlaywrightConfig({
      baseURL: opts.baseURL,
      testDir: opts.specDir,
      testMatch: opts.specFiles?.length ? opts.specFiles : [`${opts.axisKey}-*.spec.ts`],
      outputDir: opts.outputDir,
      storageState: opts.storageState,
    }),
    "utf8",
  );

  const reportPath = path.join(opts.outputDir, "report.json");

  const cli = opts.playwrightBin ?? resolvePlaywrightCli();
  if (!cli) {
    return {
      results: { passed: 0, failed: 0, skipped: 0, flaky: 0, durationMs: 0 },
      exitCode: 127,
      reportPath,
      stderr: "Could not resolve @playwright/test. Install it, or pass playwrightBin explicitly.",
    };
  }

  const bin = process.execPath;
  const args = [cli, "test", "-c", configPath];
  // Escaped: a test title routinely contains regex metacharacters, and an
  // unescaped one silently matches nothing - which reads as "did not reproduce".
  if (opts.grep) args.push("--grep", escapeForGrep(opts.grep));

  log(`[${opts.axisKey}] playwright test -c ${path.basename(configPath)}`);

  const { exitCode, stderr } = await new Promise<{ exitCode: number; stderr: string }>((resolve) => {
    const child = spawn(bin, args, {
      cwd: opts.profile.project.root,
      stdio: ["ignore", "pipe", "pipe"],
      env: { ...process.env, FORCE_COLOR: "0" },
    });

    let err = "";
    child.stderr?.on("data", (b: Buffer) => {
      err += b.toString();
    });
    child.stdout?.on("data", () => {});

    const timer = opts.timeoutMs
      ? setTimeout(() => {
          child.kill("SIGKILL");
          err += `\nclarvis: axis timed out after ${opts.timeoutMs}ms`;
        }, opts.timeoutMs)
      : undefined;

    child.on("close", (code) => {
      if (timer) clearTimeout(timer);
      resolve({ exitCode: code ?? 1, stderr: err.slice(-4000) });
    });
    child.on("error", (e) => {
      if (timer) clearTimeout(timer);
      resolve({ exitCode: 127, stderr: `${err}\n${e.message}`.slice(-4000) });
    });
  });

  let results: AxisResults;
  try {
    results = parsePlaywrightReport(JSON.parse(await readFile(reportPath, "utf8")));
  } catch {
    // No parseable report means we know nothing - report it as an error rather
    // than as a clean run with zero failures.
    results = { passed: 0, failed: 0, skipped: 0, flaky: 0, durationMs: 0 };
  }

  return { results, exitCode, reportPath, stderr };
}
