#!/usr/bin/env bash
#
# Builds Clarvis.app - a launcher, not a wrapper.
#
# Double-clicking starts the local server and opens the dashboard in the
# default browser. No Electron, no Rust, no bundled runtime: the server is the
# CLI that is already here.
#
# Two traps this works around, both found by testing rather than by reasoning:
#
#   1. An app launched from Finder inherits a minimal PATH, so a node installed
#      via nvm or Homebrew is invisible to it. The interpreter is resolved now,
#      at build time, and written into the launcher.
#
#   2. Backgrounding the server and exiting looks tidier but does not work:
#      macOS reaps the launcher once it considers the app finished, which killed
#      the browser-opening step and left an orphaned server behind. The app
#      process therefore BECOMES the server, and quitting the app stops it.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/build"
APP="${1:-$HOME/Applications/Clarvis.app}"

NODE_BIN="$(command -v node)"
if [ -z "$NODE_BIN" ]; then
  echo "node not found on PATH; cannot build the launcher." >&2
  exit 1
fi

echo "  node       $NODE_BIN"
echo "  repo       $ROOT"
echo "  target     $APP"

if [ ! -f "$ROOT/packages/ui/dist/index.html" ]; then
  echo "  building   dashboard bundle..."
  (cd "$ROOT" && pnpm --filter @clarvis/ui build >/dev/null)
fi

if [ ! -f "$BUILD/Clarvis.icns" ]; then
  echo "  building   icon..."
  (cd "$ROOT" && node scripts/make-icon.mjs >/dev/null)
fi

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Clarvis</string>
  <key>CFBundleDisplayName</key><string>Clarvis</string>
  <key>CFBundleIdentifier</key><string>dev.clarvis.launcher</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundleExecutable</key><string>Clarvis</string>
  <key>CFBundleIconFile</key><string>Clarvis</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# Unquoted heredoc: NODE_BIN and ROOT are baked in now, so every RUNTIME
# variable below must be escaped.
cat > "$APP/Contents/MacOS/Clarvis" <<LAUNCHER
#!/bin/bash
# Generated by scripts/make-app.sh - regenerate rather than editing.
set -uo pipefail

NODE="$NODE_BIN"
REPO="$ROOT"
CLI="\$REPO/packages/cli/bin/clarvis.mjs"
LOG="\$HOME/Library/Logs/Clarvis.log"
CONFIG="\$HOME/.clarvis/app.json"
PORT=4477
PROJECT="\$REPO"

mkdir -p "\$(dirname "\$LOG")"
echo "--- \$(date '+%Y-%m-%d %H:%M:%S') launch ---" >> "\$LOG"

# Which project the dashboard shows, and on which port. Editable without
# rebuilding the app.
if [ -f "\$CONFIG" ]; then
  CFG_PROJECT=\$("\$NODE" -e 'try{const c=require(process.argv[1]);if(c.project)process.stdout.write(String(c.project))}catch{}' "\$CONFIG" 2>/dev/null || true)
  CFG_PORT=\$("\$NODE" -e 'try{const c=require(process.argv[1]);if(c.port)process.stdout.write(String(c.port))}catch{}' "\$CONFIG" 2>/dev/null || true)
  [ -n "\$CFG_PROJECT" ] && PROJECT="\$CFG_PROJECT"
  [ -n "\$CFG_PORT" ] && PORT="\$CFG_PORT"
fi

URL="http://localhost:\$PORT"
echo "project=\$PROJECT port=\$PORT" >> "\$LOG"

if curl -sf -o /dev/null --max-time 1 "\$URL/api/runs" 2>/dev/null; then
  echo "already running; opening browser" >> "\$LOG"
  open "\$URL"
  exit 0
fi

# exec, not background - see the note at the top of make-app.sh. The server
# opens the browser itself once it is genuinely listening, so the browser never
# races ahead to a connection-refused page.
echo "starting server" >> "\$LOG"
exec "\$NODE" "\$CLI" ui --project "\$PROJECT" --port "\$PORT" --open >> "\$LOG" 2>&1
LAUNCHER

chmod +x "$APP/Contents/MacOS/Clarvis"
cp "$BUILD/Clarvis.icns" "$APP/Contents/Resources/Clarvis.icns"

# Nudges Finder to pick up the icon rather than showing a stale cached one.
touch "$APP"

echo ""
echo "  built      $APP"
echo "  log        ~/Library/Logs/Clarvis.log"
echo "  config     ~/.clarvis/app.json   {\"project\":\"/path/to/repo\",\"port\":4477}"
echo ""
